export const HYMNS_AND_CLASSICS = [
  {
    id: '1-hac-llc-victory-in-jesus',
    artist: 'Literal Life Church',
    title: 'Victory In Jesus',
    url: './hymns-and-classics/01 - Literal Life Church - Victory In Jesus.mp3',
  },
  {
    id: '2-hac-llc-what-a-friend-we-have-in-jesus',
    artist: 'Literal Life Church',
    title: 'What A Friend We Have In Jesus',
    url: './hymns-and-classics/02 - Literal Life Church - What A Friend We Have In Jesus.mp3',
  },
  {
    id: '3-hac-llc-how-great-thou-art',
    artist: 'Literal Life Church',
    title: 'How Great Thou Art',
    url: './hymns-and-classics/03 - Literal Life Church - How Great Thou Art.mp3',
  },
  {
    id: '4-hac-llc-blessed-assurance',
    artist: 'Literal Life Church',
    title: 'Blessed Assurance',
    url: './hymns-and-classics/04 - Literal Life Church - Blessed Assurance.mp3',
  },
  {
    id: '5-hac-llc-tis-so-sweet',
    artist: 'Literal Life Church',
    title: "'Tis So Sweet",
    url: "./hymns-and-classics/05 - Literal Life Church - 'Tis So Sweet.mp3",
  },
  {
    id: '6-hac-llc-lord-i-need-thee',
    artist: 'Literal Life Church',
    title: 'Lord I Need Thee',
    url: './hymns-and-classics/06 - Literal Life Church - Lord I Need Thee.mp3',
  },
  {
    id: '7-hac-llc-old-rugged-cross',
    artist: 'Literal Life Church',
    title: 'Old Rugged Cross',
    url: './hymns-and-classics/07 - Literal Life Church - Old Rugged Cross.mp3',
  },
  {
    id: '8-hac-llc-the-blood-will-never-loose-its-power',
    artist: 'Literal Life Church',
    title: 'The Blood Will Never Lose Its Power',
    url: './hymns-and-classics/08 - Literal Life Church - The Blood Will Never Lose Its Power.mp3',
  },
  {
    id: '9-hac-llc-power-in-the-blood',
    artist: 'Literal Life Church',
    title: 'Power In The Blood',
    url: './hymns-and-classics/09 - Literal Life Church - Power In The Blood.mp3',
  },
  {
    id: '10-hac-llc-great-is-thy-faithfulness',
    artist: 'Literal Life Church',
    title: 'Great Is Thy Faithfulness',
    url: './hymns-and-classics/10 - Literal Life Church - Great Is Thy Faithfulness.mp3',
  },
  {
    id: '11-hac-llc-when-we-all-get-to-heaven',
    artist: 'Literal Life Church',
    title: 'When We All Get To Heaven',
    url: './hymns-and-classics/11 - Literal Life Church - When We All Get To Heaven.mp3',
  },
  {
    id: '12-hac-llc-just-a-closer-walk',
    artist: 'Literal Life Church',
    title: 'Just A Closer Walk',
    url: './hymns-and-classics/12 - Literal Life Church - Just A Closer Walk.mp3',
  },
  {
    id: '13-hac-llc-the-love-of-god',
    artist: 'Literal Life Church',
    title: 'The Love Of God',
    url: './hymns-and-classics/13 - Literal Life Church - The Love Of God.mp3',
  },
  {
    id: '14-hac-llc-well-talk-it-over',
    artist: 'Literal Life Church',
    title: "We'll Talk It Over",
    url: "./hymns-and-classics/14 - Literal Life Church - We'll Talk It Over.mp3",
  },
  {
    id: '15-hac-llc-glory-land',
    artist: 'Literal Life Church',
    title: 'Glory Land',
    url: './hymns-and-classics/15 - Literal Life Church - Glory Land.mp3',
  },
  {
    id: '16-hac-llc-in-the-garden',
    artist: 'Literal Life Church',
    title: 'In The Garden',
    url: './hymns-and-classics/16 - Literal Life Church - In The Garden.mp3',
  },
  {
    id: '17-hac-llc-it-is-well',
    artist: 'Literal Life Church',
    title: 'It Is Well',
    url: './hymns-and-classics/17 - Literal Life Church - It Is Well.mp3',
  },
  {
    id: '18-hac-llc-i-stand-amazed',
    artist: 'Literal Life Church',
    title: 'I Stand Amazed',
    url: './hymns-and-classics/18 - Literal Life Church - I Stand Amazed.mp3',
  },
  {
    id: '19-hac-llc-ill-fly-away',
    artist: 'Literal Life Church',
    title: "I'll Fly Away",
    url: "./hymns-and-classics/19 - Literal Life Church - I'll Fly Away.mp3",
  },
];
