export const HYMNS_AND_CLASSICS = [
  {
    id: '1-hac-llc-victory-in-jesus',
    artist: 'Literal Life Church',
    title: 'Victory In Jesus',
    url: '/music/hymns-and-classics/victory-in-jesus.mp3',
  },
  {
    id: '2-hac-llc-what-a-friend-we-have-in-jesus',
    artist: 'Literal Life Church',
    title: 'What A Friend We Have In Jesus',
    url: '/music/hymns-and-classics/what-a-friend-we-have-in-jesus.mp3',
  },
  {
    id: '3-hac-llc-how-great-thou-art',
    artist: 'Literal Life Church',
    title: 'How Great Thou Art',
    url: '/music/hymns-and-classics/how-great-thou-art.mp3',
  },
  {
    id: '4-hac-llc-blessed-assurance',
    artist: 'Literal Life Church',
    title: 'Blessed Assurance',
    url: '/music/hymns-and-classics/blessed-assurance.mp3',
  },
  {
    id: '5-hac-llc-tis-so-sweet',
    artist: 'Literal Life Church',
    title: "'Tis So Sweet",
    url: '  /tis-so-sweet.mp3',
  },
  {
    id: '6-hac-llc-lord-i-need-thee',
    artist: 'Literal Life Church',
    title: 'Lord I Need Thee',
    url: '/music/hymns-and-classics/lord-i-need-thee.mp3',
  },
  {
    id: '7-hac-llc-old-rugged-cross',
    artist: 'Literal Life Church',
    title: 'Old Rugged Cross',
    url: '/music/hymns-and-classics/old-rugged-cross.mp3',
  },
  {
    id: '8-hac-llc-the-blood-will-never-loose-its-power',
    artist: 'Literal Life Church',
    title: 'The Blood Will Never Lose Its Power',
    url: '/music/hymns-and-classics/the-blood-will-never-lose-its-power.mp3',
  },
  {
    id: '9-hac-llc-power-in-the-blood',
    artist: 'Literal Life Church',
    title: 'Power In The Blood',
    url: '/music/hymns-and-classics/power-in-the-blood.mp3',
  },
  {
    id: '10-hac-llc-great-is-thy-faithfulness',
    artist: 'Literal Life Church',
    title: 'Great Is Thy Faithfulness',
    url: '/music/hymns-and-classics/great-is-thy-faithfulness.mp3',
  },
  {
    id: '11-hac-llc-when-we-all-get-to-heaven',
    artist: 'Literal Life Church',
    title: 'When We All Get To Heaven',
    url: '/music/hymns-and-classics/when-we-all-get-to-heaven.mp3',
  },
  {
    id: '12-hac-llc-just-a-closer-walk',
    artist: 'Literal Life Church',
    title: 'Just A Closer Walk',
    url: '/music/hymns-and-classics/just-a-closer-walk.mp3',
  },
  {
    id: '13-hac-llc-the-love-of-god',
    artist: 'Literal Life Church',
    title: 'The Love Of God',
    url: '/music/hymns-and-classics/the-love-of-god.mp3',
  },
  {
    id: '14-hac-llc-well-talk-it-over',
    artist: 'Literal Life Church',
    title: "We'll Talk It Over",
    url: '/music/hymns-and-classics/well-talk-it-over.mp3',
  },
  {
    id: '15-hac-llc-glory-land',
    artist: 'Literal Life Church',
    title: 'Glory Land',
    url: '/music/hymns-and-classics/glory-land.mp3',
  },
  {
    id: '16-hac-llc-in-the-garden',
    artist: 'Literal Life Church',
    title: 'In The Garden',
    url: '/music/hymns-and-classics/in-the-garden.mp3',
  },
  {
    id: '17-hac-llc-it-is-well',
    artist: 'Literal Life Church',
    title: 'It Is Well',
    url: '/music/hymns-and-classics/it-is-well.mp3',
  },
  {
    id: '18-hac-llc-i-stand-amazed',
    artist: 'Literal Life Church',
    title: 'I Stand Amazed',
    url: '/music/hymns-and-classics/i-stand-amazed.mp3',
  },
  {
    id: '19-hac-llc-ill-fly-away',
    artist: 'Literal Life Church',
    title: "I'll Fly Away",
    url: '/music/hymns-and-classics/ill-fly-away.mp3',
  },
];
